require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ApprovalsController do

  def mock_approval(stubs={})
    @mock_approval ||= mock_model(Approval, stubs).as_null_object
  end

  describe "GET new" do
    it "assigns a new approval as @approval" do
      Approval.stub(:new) { mock_approval }
      get :new
      assigns(:approval).should be(mock_approval)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created approval as @approval" do
        Approval.stub(:new).with({'these' => 'params'}) { mock_approval(:save => true) }
        post :create, :approval => {'these' => 'params'}
        assigns(:approval).should be(mock_approval)
      end

      it "redirects to the created approval" do
        Approval.stub(:new) { mock_approval(:save => true) }
        post :create, :approval => {}
        response.should redirect_to(approval_url(mock_approval))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved approval as @approval" do
        Approval.stub(:new).with({'these' => 'params'}) { mock_approval(:save => false) }
        post :create, :approval => {'these' => 'params'}
        assigns(:approval).should be(mock_approval)
      end

      it "re-renders the 'new' template" do
        Approval.stub(:new) { mock_approval(:save => false) }
        post :create, :approval => {}
        response.should render_template("new")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested approval" do
      Approval.stub(:find).with("37") { mock_approval }
      mock_approval.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the approvals list" do
      Approval.stub(:find) { mock_approval }
      delete :destroy, :id => "1"
      response.should redirect_to(approvals_url)
    end
  end

end
